services:
  caddy:
    image: caddy:2.9.1-alpine
    container_name: caddy
    ports:
      - 80:80
      # - 443:443
      # - 443:443/udp
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - html:/var/www/html
      - caddy_data:/data
      - caddy_config:/config
    # network_mode: host

networks:
  default:
    external: true
    name: devops-reverse-proxy

volumes:
  html:
  caddy_data:
  caddy_config:
